### ISSUE TITLE
Installation klappt nicht ?!

### ISSUE THREAD

**Issue by vanilla-thunder** [KristianH/admin-theme-manager#1]
ich habs eben in einem taufrischen 6.irgendwas.irgendwas Shop installiert und sofort nach dem Aktivieren ist Admin tot.
Mein verdacht ist, dass es an dem fehlenden Fallback fürs Admin Theme liegt. D.h. früher war "admin" hardcoded und nun ist ``$oConfig->getConfigParam('sAdminTheme')`` mehr oder weniger hardcoded. Und sofern ``sAdminTheme`` nicht gesetzt ist, sind die Pfade kaputt und er nimmt nicht mal mehr admin theme.

Folgendes hat spontan Abhilfe geschaffen:
*Core/Config.php* Zeile 36
``$theme = ($sAdminTheme = $this->getConfigParam('sAdminTheme') ? $sAdminTheme : 'admin');``
*Core/Language.php* Zeile 13:
``$sTheme = ($sAdminTheme = $oConfig->getConfigParam('sAdminTheme') ? $sAdminTheme : 'admin');``

Admin ist wieder aufrufbar, allerdings ist die Liste der verfügbaren Sprachen beim Admin Login leer, es wird aber Deutsch geladen.

**Comment by KristianH** [comment]
Erledigt. [#e3de84d](https://github.com/KristianH/admin-theme-manager/commit/e3de84d376af6aa706b1c1480f73fd544bc00b0c)

Ich habe es über eine Installations-Routine gelöst.
